"""Data loading helpers for the Week 4 dashboard.

Everything here reads the already-processed CSVs from the notebook pipeline
(data/processed/*.csv) — the dashboard doesn't recompute cleaning, anomaly
detection, or model fitting itself. That keeps the app fast and guarantees
it always shows exactly what the notebooks produced.
"""
from pathlib import Path

import pandas as pd
import streamlit as st

DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "processed"


@st.cache_data
def load_daily() -> pd.DataFrame:
    df = pd.read_csv(DATA_DIR / "supply_chain_daily.csv", parse_dates=["date"])
    return df.sort_values(["product_category", "date"]).reset_index(drop=True)


@st.cache_data
def load_anomalies() -> pd.DataFrame:
    df = pd.read_csv(DATA_DIR / "anomalies.csv", parse_dates=["date"])
    return df.sort_values(["product_category", "date"]).reset_index(drop=True)


@st.cache_data
def load_baseline_forecast() -> pd.DataFrame:
    return pd.read_csv(DATA_DIR / "baseline_forecast.csv", parse_dates=["date"])


@st.cache_data
def load_arima_forecast() -> pd.DataFrame:
    return pd.read_csv(DATA_DIR / "arima_forecast.csv", parse_dates=["date"])


@st.cache_data
def load_model_comparison() -> pd.DataFrame:
    return pd.read_csv(DATA_DIR / "model_comparison.csv")


def data_is_available() -> bool:
    """True only if every file the dashboard needs has been generated by the notebooks."""
    required = [
        "supply_chain_daily.csv",
        "anomalies.csv",
        "baseline_forecast.csv",
        "arima_forecast.csv",
        "model_comparison.csv",
    ]
    return all((DATA_DIR / name).exists() for name in required)
